export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const POST_MESSAGE = 'POST_MESSAGE';

export const AUTH_CONNECTING = 'AUTH_CONNECTING';
export const AUTH_CONNECTED = 'AUTH_CONNECTED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const FRIEND_CONNECT = 'FRIEND_CONNECT';
export const FRIEND_DISCONNECT = 'FRIEND_DISCONNECT';
export const SELECT_FRIEND = 'SELECT_FRIEND';

export const FETCH_HISTORY = 'FETCH_HISTORY';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';
export const FETCH_HISTORY_ERROR = 'FETCH_HISTORY_ERROR';
